name: publish

on:
  push:
    tags: ["v*"]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  pypi:
    needs: test
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv build
      - run: uv publish
